### ISSUE TITLE
sementation fault

### ISSUE THREAD

**Issue by laDok8** [ibenes/freecell#1]
program crashes (running with dummy solver option) unless `mem-limit` is specifed

**Comment by laDok8** [comment]
after further investigation argparsers get method fails due i assume inccorect template type cast

**Comment by ibenes** [comment]
Fixed with [89d76280ccde81699cacb699f63cc114f59bae7f](https://github.com/ibenes/freecell/commit/89d76280ccde81699cacb699f63cc114f59bae7f).
